# —————————— Profile —————————— #
# language
language: en
# avatar
avatar: img/assets/cat.png
# author
author: longlongyu
# signature
signature: for me
# friends
friends:
  friendA: //github.com/Longlongyu
  friendB: //github.com/
  friendC: //github.com/
# SNS
social:
  email: 
  github: //github.com/
  weibo: //www.weibo.com
  facebook: //www.facebook.com
  twitter: //twitter.com
  rss: /atom.xml

# —————————— Site —————————— #
# title of the site
SEO_title: Mr.Long's Blog
# main title
main_title: Mr.Long's Blog
# subtitle
subtitle: Welcome to my Blog!
# site haeder image
site_header_image: '/img/intro/index-bg.png'
# post haeder image
post_header_image:
# about image
about_header_image: 

# —————————— Indivdual —————————— #
# Miscelaneous
favicon: /img/assets/favicon.ico
# —————————— Option —————————— #
# truncate length of abstracts in index page (the default is 300, there will be no abstruct if you input 0)
truncate_length: 
# intro height (the default is 70 percents of the screen)
intro_height: 70
# enable toc
toc: true
# word count & reading time
reading_info: false
# enable Busuanzi analytics
busuanzi: true
# display updated time, if the post dose not define 'updated', the system modification time will be displayed.
display_updated: false
# copyright
copyright:
  enable: true
  # https://creativecommons.org/
  license: All articles in this blog are licensed under <a rel="license" href="https://creativecommons.org/licenses/by-nc-nd/3.0">CC BY-NC-SA 3.0</a> unless stating additionally.
# comment
comment:
  # Livere  site: https://livere.com/
  livere_uid:
  # Disqus  site: https://disqus.com/
  disqus_shortname: 
  # Changyan  site: http://changyan.kuaizhan.com/
  changyan_appid: 
  changyan_conf: 

# —————————— Others —————————— #
# main menu navigation
menu:
  Home: /
  About: /about
  Archives: /archives
  Tags: /tags
# stylesheets loaded in the <head>
stylesheets:
- /css/style.css?v=2018.7.9
- /css/animation.css?v=2018.7.9
# scripts loaded in the end of the body
scripts:
- /js/main.js?v=2018.7.9
