# —————————— Profile —————————— #
# language
language: en
# avatar
avatar: img/assets/favicon_32x32_bear.png
# author
author: Lebear
# signature
signature: If you don't like the world, create one instead of complaining.
# friends
#friends:
#  friendB: //github.com/
#  friendC: //github.com/
# SNS
social:
  email: //lebear.top@gmail.com
  github: //github.com/leisurelybear
  #weibo: //www.weibo.com
  #facebook: //www.facebook.com
  #twitter: //twitter.com
  #rss: /atom.xml

# —————————— Site —————————— #
# title of the site
SEO_title: LeisurelyBear Blog
# main title
main_title: LeisurelyBear's Blog
# subtitle
subtitle: Love Life, Follow Technology. 
# site haeder image
site_header_image: '/img/intro/index-bg.jpg'
# post haeder image
post_header_image:
# about image
about_header_image: 

# —————————— Indivdual —————————— #
# Miscelaneous
favicon: /img/assets/favicon.ico
# —————————— Option —————————— #
# truncate length of abstracts in index page (the default is 300, there will be no abstruct if you input 0)
truncate_length: 
# intro height (the default is 70 percents of the screen)
intro_height: 80
# enable toc
toc: true
# word count & reading time
reading_info: true
# access statistics
count:
  # enable analytics
  # true or flase
  busuanzi: true
# Time
# you can modify the timestamp format.
date_format: YYYY-MM-DD
# display created time.
display_created: true
# display updated time, if the post dose not define 'updated', the system modification time will be displayed.
display_updated: false
# copyright
copyright:
  enable: true
  # https://creativecommons.org/
  license: Copyright © 2019-2022 LeisurelyBear All rights reserved.
# comment
comment:
  # Livere  site: https://livere.com/
  livere_uid:
  # Disqus  site: https://disqus.com/
  disqus_shortname: 
  # Changyan  site: http://changyan.kuaizhan.com/
  changyan_appid: 
  changyan_conf: 
  # Gitment  site: https://github.com/imsun/gitment/
  gitment_owner: Leisurelybear
  gitment_repo: blog.lebear.top-comment
  gitment_client_id: 7b32efbea888ff18bf71
  gitment_client_secret: d6d9022e73dfc0e9e55dc8ad8604a5aa73447595

# —————————— Others —————————— #
# main menu navigation
menu:
  Home: /
  About: /about/
  Archives: /archives/
  Tags: /tags/
  Friends: /friends/
# stylesheets loaded in the <head>
stylesheets:
- /css/style.css?v=2018.7.9
- /css/animation.css?v=2018.7.9
- /css/szgotop.css
# scripts loaded in the end of the body
scripts:
- /js/main.js?v=2018.7.9
- /js/szgotop.js
